apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: upf-edge-1 
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|upf-example|upf-example'
spec:
  provider: upf.free5gc.io

